version: "3.8"

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: call_router_dev
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev123
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U dev -d call_router_dev"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
